#!/usr/bin/env bash
#
# scripts/build_macos.sh
#
# Builds a release macOS .app bundle for AniMeow (animeko_flutter).
#
# What it does:
#   1. rm -rf macos/Flutter/ephemeral                      (drop generated Xcode/SwiftPM state;
#                                                           it is gitignored and fully regenerated
#                                                           by pub get — see note below)
#   2. flutter pub get                                   (ensure deps match pubspec.lock)
#   3. dart run build_runner build --delete-conflicting-outputs
#                                                          (regenerate *.g.dart before compiling,
#                                                           so a stale codegen file never silently
#                                                           ships in the built app)
#   4. flutter build macos --release                       (produce the .app bundle)
#
# Why step 1 exists:
#   flutter pub get does NOT rewrite macos/Flutter/ephemeral/Flutter-Generated.xcconfig
#   or flutter_export_environment.sh when they already exist, so a FLUTTER_ROOT
#   (and SwiftPM vs CocoaPods plugin layout) written by a *different* Flutter SDK
#   sticks around and breaks the build with errors like:
#     target 'wakelock_plus' referenced in product 'wakelock-plus' is empty
#   Purging the directory makes every build start from the SDK on PATH.
#
# Usage:
#   ./scripts/build_macos.sh
#
# The resulting .app is left at:
#   build/macos/Build/Products/Release/AniMeow.app
#
# Run this script from anywhere; it always operates relative to the repo root
# (determined from this script's own location), not the caller's cwd.

set -euo pipefail

# Resolve the repo root as the parent of this script's directory, so the
# script works correctly no matter where it's invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

APP_NAME="AniMeow.app"
APP_PATH="build/macos/Build/Products/Release/${APP_NAME}"

# Log which toolchain is actually being used — makes a mismatched SDK obvious in
# build logs when several developers (or several local installs) are involved.
echo "==> flutter: $(command -v flutter)"
flutter --version | head -n 1

echo "==> [1/4] purge macos/Flutter/ephemeral (regenerated by pub get)"
rm -rf macos/Flutter/ephemeral

echo "==> [2/4] flutter pub get"
flutter pub get

echo "==> [3/4] dart run build_runner build --delete-conflicting-outputs"
dart run build_runner build --delete-conflicting-outputs

echo "==> [4/4] flutter build macos --release"
flutter build macos --release

if [ -d "${APP_PATH}" ]; then
  echo ""
  echo "Build succeeded:"
  echo "  ${REPO_ROOT}/${APP_PATH}"
  echo ""
  echo "Open it with:"
  echo "  open \"${REPO_ROOT}/${APP_PATH}\""
else
  echo "ERROR: expected app bundle not found at ${APP_PATH}" >&2
  exit 1
fi
